In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("churn.csv")

In [6]:
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,NaN,2208.32,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,996,42,Male,41,37.14,Month-to-Month,Fiber Optic,1522.74,Yes,Yes
996,997,62,Male,9,80.93,Month-to-Month,NaN,728.37,No,Yes
997,998,51,Female,15,111.72,Month-to-Month,Fiber Optic,1675.80,Yes,Yes
998,999,39,Male,68,65.67,One-Year,NaN,4465.56,No,Yes
999,1000,50,Male,1,56.67,Month-to-Month,NaN,56.67,No,Yes

In [9]:
df.head(5)

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,NaN,2208.32,No,Yes

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1000 non-null   int64
 1   Age              1000 non-null   int64
 2   Gender           1000 non-null   object
 3   Tenure           1000 non-null   int64
 4   MonthlyCharges   1000 non-null   float64
 5   ContractType     1000 non-null   object
 6   InternetService  1000 non-null   object
 7   TotalCharges     1000 non-null   float64
 8   TechSupport      1000 non-null   object
 9   Churn            1000 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 78.3+ KB

In [ ]:
df.isna().sum().sum()
#df.insa() tell missing values in each column by true or false
#df.insa().sum() count the number of true values in each column which is the number of missing values in each column by giving 0 or 1 
#df.isna().sum().sum() count the total number of missing values in the whole dataset by giving a single number

0

In [ ]:
df["InternetService"]=df["InternetService"].fillna("No")
#df["InternetService"]=df["InternetService"].fillna("No") used to fill the missing values in the "InternetService" column with "No" because it is a categorical column and "No" is a valid category for it. This way we can handle the missing values without losing any data.

In [35]:
df.duplicated().sum()
#Checks each row in the DataFrame
#If a row is duplicate (same as a previous row) → True
#If unique → False

0

In [30]:
df.head()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,No,2208.32,No,Yes

In [ ]:
df.describe()
#It calculates these values for each numeric column:
count → total non-missing values
#mean → average value
#std → standard deviation (spread of data)
#min → smallest value
#25% → 1st quartile
#50% → median
#75% → 3rd quartile
#max → largest value

        CustomerID          Age      Tenure  MonthlyCharges  TotalCharges
count  1000.000000  1000.000000  1000.00000     1000.000000   1000.000000
mean    500.500000    44.674000    18.97300       74.391290   1404.364060
std     288.819436     9.797741    18.89257       25.712083   1571.755048
min       1.000000    12.000000     0.00000       30.000000      0.000000
25%     250.750000    38.000000     5.00000       52.357500    345.217500
50%     500.500000    45.000000    13.00000       74.060000    872.870000
75%     750.250000    51.000000    26.00000       96.102500   1900.175000
max    1000.000000    83.000000   122.00000      119.960000  12416.250000

In [ ]:
numeric_coloumn_data = df.select_dtypes(include=["number"])
numeric_coloumn_data.corr()
#numeric_coloumn_data = df.select_dtypes(include=["number"])creates a new DataFrame with only numeric columns
#numeric_coloumn_data.corr()
#Tell me how strongly each numeric column is related to every other numeric column”
#If Age ↑ → Salary ↑ → positive correlation
#If Marks ↑ → Rank ↓ → negative correlation
#If Height vs Exam Marks → no correlation

                CustomerID       Age    Tenure  MonthlyCharges  TotalCharges
CustomerID        1.000000  0.036730 -0.018585       -0.030504     -0.027490
Age               0.036730  1.000000  0.000472        0.006362     -0.001896
Tenure           -0.018585  0.000472  1.000000       -0.014552      0.894868
MonthlyCharges   -0.030504  0.006362 -0.014552        1.000000      0.304893
TotalCharges     -0.027490 -0.001896  0.894868        0.304893      1.000000

In [36]:
df["Churn"].value_counts()

Churn
Yes    883
No     117
Name: count, dtype: int64